wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683715142.611345
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.10
      5: 0.15.2
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
