FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# Set Timezone to Asia/Seoul
ENV TZ=Asia/Seoul
RUN apt-get -y update &&\
  apt-get -y upgrade &&\
  apt-get -yq install tzdata &&\
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&\
  echo $TZ > /etc/timezone &&\
  dpkg-reconfigure -f noninteractive tzdata

# Install essential packages
RUN apt-get install -y \
  software-properties-common \
  python3-software-properties

# Change python version to 3.11
RUN add-apt-repository ppa:deadsnakes/ppa &&\
  apt-get install -y \
  python3.11 \
  python3.11-distutils \
  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 \
  curl -sS https://bootstrap.pypa.io/get-pip.py | python

# Install Graph-Tool
RUN apt-get install -f &&\
  python -m pip install --upgrade pip setuptools wheel &&\
  apt-key adv --keyserver keyserver.ubuntu.com --recv-key 612DEFB798507F25 &&\
  add-apt-repository "deb https://downloads.skewed.de/apt buster main" &&\
  apt-get update &&\
  apt-get -t buster -yf install python3-graph-tool

# Install python packages and pytorch
COPY ./requirements.txt ./
RUN python -m pip install -r requirements.txt &&\
  python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

COPY . .