wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683714778.772025
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.10
      5: 0.15.2
      8:
      - 5
